### ISSUE TITLE
No longer works with open3d 0.9

### ISSUE THREAD

**Issue by airfield20** [felixchenfy/open3d_ros_pointcloud_conversion#1]
In 0.9 open3d function calls are grouped into categories.
Simply changing all similar occurrences of `open3d.read_point_cloud(...)` to `open3d.io.read_point_cloud(...)` fixed the syntax issue. When running the tests, an empty cloud is being published, so the conversions do not work.

I am using Ubuntu 18 on ROS Melodic with open3d 0.9.

Edit: Relevant Error message: 
```
Traceback (most recent call last):
  File "/home/aaron/bedestrian_ws/src/open3d_ros_pointcloud_conversion/lib_cloud_conversion_between_Open3D_and_ROS.py", line 120, in <module>
    open3d_cloud = open3d.read_point_cloud(filename)
AttributeError: 'module' object has no attribute 'read_point_cloud'
```

**Comment by fwarmuth** [comment]
you can easily port that. But there are still problems regarding colors within point clouds...
maybe i figure it out and do a pullrequest

**Comment by airfield20** [comment]
I'm no longer working with open3d

**Comment by fwarmuth** [comment]
what library are using now?
